#include "elf-output.h"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include <sys/stat.h>
#include <unistd.h>

#ifndef SRC_DIR
#error "SRC_DIR must be defined at compile time"
#endif

static bool run_cmd(const std::string& cmd, bool verbose) {
    if (verbose)
        printf("  $ %s\n", cmd.c_str());
    int rc = system(cmd.c_str());
    if (rc != 0) {
        fprintf(stderr, "command failed (rc=%d): %s\n", rc, cmd.c_str());
        return false;
    }
    return true;
}

static bool write_file(const std::string& path, const char* data, size_t len) {
    FILE* f = fopen(path.c_str(), "wb");
    if (!f) {
        perror(path.c_str());
        return false;
    }
    size_t written = fwrite(data, 1, len, f);
    fclose(f);
    return written == len;
}

static bool write_string(const std::string& path, const std::string& content) {
    return write_file(path, content.data(), content.size());
}

// Write all translated function .o files to the temp directory.
static std::vector<std::string> write_obj_files(
        const TranslationResult& result, const std::string& tmpdir,
        bool verbose) {
    std::vector<std::string> paths;
    for (const auto& tf : result.functions) {
        if (!tf.success)
            continue;
        char name[64];
        snprintf(name, sizeof(name), "func_%lx.o", (unsigned long)tf.guest_addr);
        std::string path = tmpdir + "/" + name;
        if (!write_file(path, tf.obj_code.data(), tf.obj_code.size())) {
            fprintf(stderr, "error: failed to write %s\n", path.c_str());
            continue;
        }
        paths.push_back(path);
        if (verbose)
            printf("  wrote %s (%zu bytes)\n", name, tf.obj_code.size());
    }
    return paths;
}

struct AddrSymbol {
    uint64_t guest_addr;
    std::string symbol;
};

static std::vector<AddrSymbol> collect_symbols(const TranslationResult& result) {
    std::vector<AddrSymbol> syms;
    for (const auto& tf : result.functions) {
        if (!tf.success)
            continue;
        char sym[64];
        snprintf(sym, sizeof(sym), "aot_%lx", (unsigned long)tf.guest_addr);
        syms.push_back({tf.guest_addr, sym});
    }
    std::sort(syms.begin(), syms.end(),
              [](const AddrSymbol& a, const AddrSymbol& b) {
                  return a.guest_addr < b.guest_addr;
              });
    return syms;
}

// Generate glue.S: _start, helper trampolines, libc replacements, address table.
static std::string generate_glue_asm(const std::vector<AddrSymbol>& syms,
                                     uint64_t entry_addr) {
    std::string s;
    s += "// Generated by instrew-aot\n";
    s += ".text\n";

    // _start entry point
    s += ".globl _start\n";
    s += ".type _start, %function\n";
    s += "_start:\n";
    s += "    mov x29, #0\n";
    s += "    mov x30, #0\n";
    s += "    mov x0, sp\n";
    s += "    bl aot_main\n";
    s += "    mov x8, #93\n";
    s += "    svc #0\n";
    s += "\n";

    // Trampolines for translated code's helper references
    s += ".globl syscall\n";
    s += ".type syscall, %function\n";
    s += "syscall:\n";
    s += "    b aot_syscall\n";
    s += "\n";

    s += ".globl cpuid\n";
    s += ".type cpuid, %function\n";
    s += "cpuid:\n";
    s += "    b aot_cpuid\n";
    s += "\n";

    // Minimal memset (byte-by-byte) — replaces glibc's IFUNC memset
    s += ".globl memset\n";
    s += ".type memset, %function\n";
    s += "memset:\n";
    s += "    cbz x2, 1f\n";
    s += "    mov x3, x0\n";
    s += "0:  strb w1, [x3], #1\n";
    s += "    subs x2, x2, #1\n";
    s += "    b.ne 0b\n";
    s += "1:  ret\n";
    s += "\n";

    // Minimal memcpy (byte-by-byte)
    s += ".globl memcpy\n";
    s += ".type memcpy, %function\n";
    s += "memcpy:\n";
    s += "    cbz x2, 1f\n";
    s += "    mov x3, x0\n";
    s += "0:  ldrb w4, [x1], #1\n";
    s += "    strb w4, [x3], #1\n";
    s += "    subs x2, x2, #1\n";
    s += "    b.ne 0b\n";
    s += "1:  ret\n";
    s += "\n";

    // _exit via raw syscall
    s += ".globl _exit\n";
    s += ".type _exit, %function\n";
    s += "_exit:\n";
    s += "    mov x8, #93\n";
    s += "    svc #0\n";
    s += "\n";

    // aot_write_stderr(const char* msg, unsigned long len) — raw write to fd 2
    s += ".globl aot_write_stderr\n";
    s += ".type aot_write_stderr, %function\n";
    s += "aot_write_stderr:\n";
    s += "    mov x2, x1\n";       // len
    s += "    mov x1, x0\n";       // buf
    s += "    mov x0, #2\n";       // fd = stderr
    s += "    mov x8, #64\n";      // __NR_write on aarch64
    s += "    svc #0\n";
    s += "    ret\n";
    s += "\n";

    // Address table in .rodata
    s += ".section .rodata\n";
    s += ".balign 8\n";

    s += ".globl aot_address_table\n";
    s += "aot_address_table:\n";
    for (const auto& sym : syms) {
        char buf[128];
        snprintf(buf, sizeof(buf), "    .quad 0x%lx\n    .quad %s\n",
                 (unsigned long)sym.guest_addr, sym.symbol.c_str());
        s += buf;
    }
    s += "\n";

    char buf[128];
    s += ".globl aot_address_table_size\n";
    s += "aot_address_table_size:\n";
    snprintf(buf, sizeof(buf), "    .quad %zu\n", syms.size());
    s += buf;
    s += "\n";

    s += ".globl aot_guest_entry\n";
    s += "aot_guest_entry:\n";
    snprintf(buf, sizeof(buf), "    .quad 0x%lx\n", (unsigned long)entry_addr);
    s += buf;

    return s;
}

// Generate aot_main.cc: standalone dispatch loop with binary search.
// Uses __builtin_memset and raw write for error output. No libc needed.
static std::string generate_aot_main() {
    std::string s;
    s += "// Generated by instrew-aot — standalone, no libc dependencies\n";
    s += "#include \"runtime.h\"\n";
    s += "\n";
    s += "extern \"C\" {\n";
    s += "    extern const uint64_t aot_address_table[];\n";
    s += "    extern const uint64_t aot_address_table_size;\n";
    s += "    extern const uint64_t aot_guest_entry;\n";
    s += "    void aot_write_stderr(const char* msg, unsigned long len);\n";
    s += "    [[noreturn]] void _exit(int status);\n";
    s += "}\n";
    s += "\n";
    s += "static TranslatedFuncPtr aot_lookup(uint64_t addr) {\n";
    s += "    uint64_t lo = 0, hi = aot_address_table_size;\n";
    s += "    while (lo < hi) {\n";
    s += "        uint64_t mid = lo + (hi - lo) / 2;\n";
    s += "        uint64_t mid_addr = aot_address_table[mid * 2];\n";
    s += "        if (mid_addr == addr)\n";
    s += "            return reinterpret_cast<TranslatedFuncPtr>(aot_address_table[mid * 2 + 1]);\n";
    s += "        if (mid_addr < addr)\n";
    s += "            lo = mid + 1;\n";
    s += "        else\n";
    s += "            hi = mid;\n";
    s += "    }\n";
    s += "    return nullptr;\n";
    s += "}\n";
    s += "\n";
    // Hex-print helper for error messages
    s += "static void write_hex(uint64_t val) {\n";
    s += "    char buf[18];\n";
    s += "    buf[0] = '0'; buf[1] = 'x';\n";
    s += "    for (int i = 15; i >= 0; i--) {\n";
    s += "        int nibble = val & 0xf;\n";
    s += "        buf[2 + i] = nibble < 10 ? '0' + nibble : 'a' + nibble - 10;\n";
    s += "        val >>= 4;\n";
    s += "    }\n";
    s += "    aot_write_stderr(buf, 18);\n";
    s += "}\n";
    s += "\n";
    s += "extern \"C\" __attribute__((noreturn))\n";
    s += "void aot_main(void* stack_ptr) {\n";
    s += "    AotCpuState cpu;\n";
    s += "    __builtin_memset(&cpu, 0, sizeof(cpu));\n";
    s += "    cpu.self = &cpu;\n";
    s += "    cpu_reg(&cpu, X86Reg::RIP) = aot_guest_entry;\n";
    s += "    cpu_reg(&cpu, X86Reg::RSP) = reinterpret_cast<uint64_t>(stack_ptr);\n";
    s += "\n";
    s += "    uint8_t* sptr = cpu.regdata;\n";
    s += "    for (;;) {\n";
    s += "        uint64_t pc = cpu_reg(&cpu, X86Reg::RIP);\n";
    s += "        TranslatedFuncPtr fn = aot_lookup(pc);\n";
    s += "        if (!fn) {\n";
    s += "            aot_write_stderr(\"aot: no translation for \", 24);\n";
    s += "            write_hex(pc);\n";
    s += "            aot_write_stderr(\"\\n\", 1);\n";
    s += "            _exit(127);\n";
    s += "        }\n";
    s += "        fn(sptr);\n";
    s += "    }\n";
    s += "}\n";
    return s;
}

static void cleanup_tmpdir(const std::string& tmpdir) {
    std::string cmd = "rm -rf " + tmpdir;
    int rc = system(cmd.c_str());
    (void)rc;
}

bool emit_aarch64_elf(const TranslationResult& result, const ElfInput& elf,
                      const char* output_path, bool verbose) {
    printf("\n=== Phase 4: ELF Output Generation ===\n");

    const std::string src_dir = SRC_DIR;

    // 1. Create temp directory
    char tmpdir_template[] = "/tmp/instrew-aot-XXXXXX";
    char* tmpdir_ptr = mkdtemp(tmpdir_template);
    if (!tmpdir_ptr) {
        perror("mkdtemp");
        return false;
    }
    std::string tmpdir(tmpdir_ptr);
    if (verbose)
        printf("Temp directory: %s\n", tmpdir.c_str());

    // 2. Write translated function .o files
    printf("Writing translated object files...\n");
    auto obj_paths = write_obj_files(result, tmpdir, verbose);
    if (obj_paths.empty()) {
        fprintf(stderr, "error: no translated functions to link\n");
        cleanup_tmpdir(tmpdir);
        return false;
    }
    printf("  %zu object files written\n", obj_paths.size());

    // 3. Collect symbols and generate glue assembly
    auto syms = collect_symbols(result);
    std::string glue_path = tmpdir + "/glue.S";
    if (!write_string(glue_path, generate_glue_asm(syms, elf.entry()))) {
        fprintf(stderr, "error: failed to write glue.S\n");
        cleanup_tmpdir(tmpdir);
        return false;
    }

    // 4. Generate aot_main.cc
    std::string main_path = tmpdir + "/aot_main.cc";
    if (!write_string(main_path, generate_aot_main())) {
        fprintf(stderr, "error: failed to write aot_main.cc\n");
        cleanup_tmpdir(tmpdir);
        return false;
    }

    // 5. Compile everything
    printf("Compiling runtime components...\n");
    std::string cc = "clang-18";
    std::string cflags = "-c -O2 -I" + src_dir;
    std::string standalone_cflags = cflags + " -DAOT_STANDALONE";

    // Assemble glue.S
    if (!run_cmd(cc + " -c " + glue_path + " -o " + tmpdir + "/glue.o", verbose)) {
        cleanup_tmpdir(tmpdir);
        return false;
    }

    // Compile aot_main.cc (with AOT_STANDALONE so runtime.h knows)
    if (!run_cmd(cc + " " + standalone_cflags + " " + main_path +
                 " -o " + tmpdir + "/aot_main.o", verbose)) {
        cleanup_tmpdir(tmpdir);
        return false;
    }

    // Compile syscall-emu.cc with AOT_STANDALONE (raw syscall, no libc)
    if (!run_cmd(cc + " " + standalone_cflags + " " +
                 src_dir + "/syscall-emu.cc -o " + tmpdir + "/syscall-emu.o",
                 verbose)) {
        cleanup_tmpdir(tmpdir);
        return false;
    }

    // Compile cpuid-emu.cc
    if (!run_cmd(cc + " " + standalone_cflags + " " +
                 src_dir + "/cpuid-emu.cc -o " + tmpdir + "/cpuid-emu.o",
                 verbose)) {
        cleanup_tmpdir(tmpdir);
        return false;
    }

    // 6. Link with -nostdlib (all helpers provided in glue.S)
    printf("Linking standalone AArch64 ELF...\n");
    std::string link_cmd = cc + " -nostdlib -static -fuse-ld=lld-18 -o " +
                           tmpdir + "/output";
    link_cmd += " " + tmpdir + "/glue.o";
    link_cmd += " " + tmpdir + "/aot_main.o";
    link_cmd += " " + tmpdir + "/syscall-emu.o";
    link_cmd += " " + tmpdir + "/cpuid-emu.o";
    for (const auto& obj : obj_paths)
        link_cmd += " " + obj;

    if (!run_cmd(link_cmd, verbose)) {
        cleanup_tmpdir(tmpdir);
        return false;
    }

    // 7. Copy result to output path
    std::string src = tmpdir + "/output";
    std::string cp_cmd = "cp " + src + " " + std::string(output_path);
    if (!run_cmd(cp_cmd, verbose)) {
        cleanup_tmpdir(tmpdir);
        return false;
    }
    chmod(output_path, 0755);

    struct stat st;
    if (stat(output_path, &st) == 0)
        printf("Output: %s (%ld bytes)\n", output_path, (long)st.st_size);
    else
        printf("Output: %s\n", output_path);

    cleanup_tmpdir(tmpdir);

    printf("Phase 4 complete.\n");
    return true;
}
